# Some useful sentence in paper
> 2017.02.27

---
> Podlubny, I., & Podlubny, L. (1999). Fractional Differential Equations. Book, 1-366. https://doi.org/10.1016/S0076-5392(99)80017-4

- It is clear from (2.8) that (i) ...
- Applying this definition twice gives the second-order derivate ...
- Relationships suggest the following general expression ...
- Relationship applied to ... gives ...
- Taking into account () and () and applying Theorem 2.1 we conclude that ...
- ... performing the substitution () we obtain ...
>Moulay, E., & Perruquetti, W. (2006). Finite time stability and stabilization of a class of continuous systems. Journal of Mathematical Analysis and Applications, 323(2), 1430–1443. https://doi.org/10.1016/j.jmaa.2005.11.046

- There is a problem which concerns ...
- ... such property is useful to ...
- The knowledge of the settling-time function and its regularity property allow to characterize the finite time stability by using Lyapunov functions.
- ... have often been a subject of research ...
- ... split the finite stability into ... and ...
- ... is equivalent to ...
- ... involving ...
- ... possess ...
- ... denote by A B ...
- ... use A to denote B...


`To be continued ... `
```
                      风是穿山过水拂面而来
                      花是零落成泥常开不败
                      雪是日出消融檐上落白
                      月是咫尺天涯千秋万载```
