# Some useful sentence in paper
> Since 2017.02.27
> Edited by Zhiqiang Ma

---
![Alt text](https://gss0.baidu.com/9fo3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/f7246b600c338744415f82d8590fd9f9d62aa0f8.jpg)
> Podlubny, I., & Podlubny, L. (1999). Fractional Differential Equations. Book, 1-366. https://doi.org/10.1016/S0076-5392(99)80017-4

- It is clear from (2.8) that (i) ...

- Applying this definition twice gives the second-order derivate ...
- Relationships suggest the following general expression ...
- Relationship applied to ... gives ...
- Taking into account () and () and applying Theorem 2.1 we conclude that ...
- ... performing the substitution () we obtain ...
- From the theoretical point of view, ...
- Noting that we have only one restriction for m in formula (2.54), ...
- Putting here s=m-1, we obtain ...
- Comparing () and () we arrive at the conclusion that ...
- The relationship () says that ...
- Examining the right-hand side of () we see that ...
- We see that the formulas () and () can be considered as particular cases one of them, ...

>Moulay, E., & Perruquetti, W. (2006). Finite time stability and stabilization of a class of continuous systems. Journal of Mathematical Analysis and Applications, 323(2), 1430–1443. https://doi.org/10.1016/j.jmaa.2005.11.046

- There is a problem which concerns ...
- ... such property is useful to ...
- The knowledge of the settling-time function and its regularity property allow to characterize the finite time stability by using Lyapunov functions.
- ... have often been a subject of research ...
- ... split the finite stability into ... and ...
- ... is equivalent to ...
- ... involving ...
- ... possess ...
- ... denote by A B ...
- ... use A to denote B...
-


`To be continued ... `
